/**
 * Acadin Question Bank Seeder
 * Seeds domain-specific interview/coding questions into MongoDB
 * Run: node scripts/seedQuestions.js
 */
require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');

const connectDB = async () => {
  const uri = process.env.MONGO_URI || process.env.MONGODB_URI;
  await mongoose.connect(uri);
  console.log('MongoDB connected to:', uri);
};

const { QuestionBank } = require('../models/SkillAssessment');

const questions = [
  // ── Web Development ───────────────────────────────────────────────────────
  { category: 'Web Development', type: 'mcq', difficulty: 'medium', question: 'What does the "box model" in CSS consist of?', options: ['content, padding, border, margin', 'header, body, footer, sidebar', 'width, height, color, font', 'block, inline, flex, grid'], correctAnswer: 'content, padding, border, margin' },
  { category: 'Web Development', type: 'mcq', difficulty: 'medium', question: 'Which HTTP status code indicates "Not Found"?', options: ['200', '301', '404', '500'], correctAnswer: '404' },
  { category: 'Web Development', type: 'mcq', difficulty: 'hard', question: 'What is the purpose of the Virtual DOM in React?', options: ['Directly updates the real DOM on every state change', 'Minimizes real DOM manipulations by diffing changes', 'Stores component state on the server', 'Compiles JSX to native mobile code'], correctAnswer: 'Minimizes real DOM manipulations by diffing changes' },
  { category: 'Web Development', type: 'mcq', difficulty: 'easy', question: 'Which CSS property is used to make a flex container?', options: ['display: flex', 'float: left', 'position: flex', 'align: flex'], correctAnswer: 'display: flex' },
  { category: 'Web Development', type: 'mcq', difficulty: 'medium', question: 'What does REST stand for?', options: ['Remote Execution State Transfer', 'Representational State Transfer', 'Reliable Event Socket Transfer', 'Resource Entity State Transfer'], correctAnswer: 'Representational State Transfer' },
  { category: 'Web Development', type: 'mcq', difficulty: 'hard', question: 'What is the time complexity of JavaScript\'s Array.prototype.sort()?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], correctAnswer: 'O(n log n)' },
  { category: 'Web Development', type: 'mcq', difficulty: 'medium', question: 'Which of the following is NOT a JavaScript data type?', options: ['undefined', 'boolean', 'float', 'symbol'], correctAnswer: 'float' },
  { category: 'Web Development', type: 'boolean', difficulty: 'easy', question: 'CSS Grid and Flexbox can be used together in the same layout.', options: ['Yes', 'No'], correctAnswer: 'Yes' },
  { category: 'Web Development', type: 'mcq', difficulty: 'medium', question: 'What does "async/await" in JavaScript help with?', options: ['Making code run faster', 'Writing asynchronous code in a synchronous style', 'Preventing memory leaks', 'Blocking the event loop'], correctAnswer: 'Writing asynchronous code in a synchronous style' },
  { category: 'Web Development', type: 'mcq', difficulty: 'hard', question: 'What is CORS and why is it important?', options: ['A CSS framework for responsive design', 'A browser security policy controlling cross-origin requests', 'A JavaScript pattern for modular code', 'A protocol for encrypting HTTP traffic'], correctAnswer: 'A browser security policy controlling cross-origin requests' },
  { category: 'Web Development', type: 'rating', difficulty: 'medium', question: 'Rate your proficiency with React.js and component lifecycle methods.', options: [] },
  { category: 'Web Development', type: 'rating', difficulty: 'medium', question: 'How comfortable are you with RESTful API design and HTTP methods?', options: [] },
  { category: 'Web Development', type: 'mcq', difficulty: 'medium', question: 'Which hook in React is used for side effects?', options: ['useState', 'useEffect', 'useContext', 'useReducer'], correctAnswer: 'useEffect' },
  { category: 'Web Development', type: 'mcq', difficulty: 'hard', question: 'What is the purpose of a service worker in a web app?', options: ['To run JavaScript on the server', 'To enable offline caching and push notifications', 'To manage database connections', 'To handle CSS animations'], correctAnswer: 'To enable offline caching and push notifications' },
  { category: 'Web Development', type: 'boolean', difficulty: 'medium', question: 'localStorage data persists even after the browser is closed.', options: ['Yes', 'No'], correctAnswer: 'Yes' },
  { category: 'Web Development', type: 'mcq', difficulty: 'easy', question: 'Which HTML tag is used to link a CSS file?', options: ['<style>', '<link>', '<script>', '<meta>'], correctAnswer: '<link>' },
  { category: 'Web Development', type: 'mcq', difficulty: 'hard', question: 'What is server-side rendering (SSR) primarily used for?', options: ['Faster development builds', 'Better SEO and initial page load performance', 'Reducing server costs', 'Simpler state management'], correctAnswer: 'Better SEO and initial page load performance' },
  { category: 'Web Development', type: 'mcq', difficulty: 'medium', question: 'In Node.js, what does the "require()" function do?', options: ['Runs a shell command', 'Imports a module or file', 'Declares a global variable', 'Connects to a database'], correctAnswer: 'Imports a module or file' },
  { category: 'Web Development', type: 'rating', difficulty: 'hard', question: 'Rate your experience with full-stack development (frontend + backend + database).', options: [] },
  { category: 'Web Development', type: 'mcq', difficulty: 'medium', question: 'What is the main advantage of using TypeScript over JavaScript?', options: ['TypeScript runs faster at runtime', 'TypeScript adds static typing for better error detection', 'TypeScript eliminates the need for a bundler', 'TypeScript compiles directly to machine code'], correctAnswer: 'TypeScript adds static typing for better error detection' },
  { category: 'Web Development', type: 'mcq', difficulty: 'hard', question: 'What is "debouncing" in JavaScript?', options: ['Removing duplicate events', 'Delaying function execution until after a period of inactivity', 'Cancelling a fetch request', 'Preventing default browser behavior'], correctAnswer: 'Delaying function execution until after a period of inactivity' },
  { category: 'Web Development', type: 'boolean', difficulty: 'easy', question: 'The <script> tag can be placed inside the <body> element.', options: ['Yes', 'No'], correctAnswer: 'Yes' },
  { category: 'Web Development', type: 'mcq', difficulty: 'medium', question: 'What does JWT stand for in web authentication?', options: ['Java Web Token', 'JSON Web Token', 'JavaScript Web Technology', 'JSON Web Transfer'], correctAnswer: 'JSON Web Token' },
  { category: 'Web Development', type: 'mcq', difficulty: 'hard', question: 'What is the difference between "==" and "===" in JavaScript?', options: ['No difference', '== checks value only; === checks value and type', '=== is used for objects only', '== is used for strict comparison'], correctAnswer: '== checks value only; === checks value and type' },
  { category: 'Web Development', type: 'rating', difficulty: 'medium', question: 'Rate your ability to debug web applications using browser DevTools.', options: [] },

  // ── DSA / Algorithms ──────────────────────────────────────────────────────
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'easy', question: 'What is the time complexity of binary search on a sorted array?', options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'], correctAnswer: 'O(log n)' },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'medium', question: 'Which data structure uses LIFO (Last In, First Out) ordering?', options: ['Queue', 'Stack', 'Heap', 'Array'], correctAnswer: 'Stack' },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'hard', question: 'What is the time complexity of Dijkstra\'s algorithm with a min-heap?', options: ['O(V²)', 'O(E log V)', 'O(V log E)', 'O(E + V)'], correctAnswer: 'O(E log V)' },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'medium', question: 'Which sorting algorithm has the best average-case time complexity?', options: ['Bubble Sort', 'Merge Sort', 'Quick Sort', 'Insertion Sort'], correctAnswer: 'Merge Sort' },
  { category: 'DSA / Algorithms', type: 'boolean', difficulty: 'easy', question: 'A binary search tree (BST) always has a time complexity of O(log n) for search.', options: ['Yes', 'No'], correctAnswer: 'No' },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'medium', question: 'What is a hash collision?', options: ['Two keys mapping to the same hash value', 'A hash function that returns null', 'Hash table running out of memory', 'Two different hash functions producing the same output'], correctAnswer: 'Two keys mapping to the same hash value' },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'hard', question: 'What is the space complexity of Merge Sort?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], correctAnswer: 'O(n)' },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'medium', question: 'Which graph traversal algorithm uses a queue (BFS)?', options: ['Depth First Search', 'Breadth First Search', 'Topological Sort', 'Bellman-Ford'], correctAnswer: 'Breadth First Search' },
  { category: 'DSA / Algorithms', type: 'rating', difficulty: 'medium', question: 'Rate your ability to solve dynamic programming problems.', options: [] },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'hard', question: 'In a max-heap, the value of each node is _____ the values of its children.', options: ['less than', 'greater than or equal to', 'equal to', 'unrelated to'], correctAnswer: 'greater than or equal to' },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'medium', question: 'What is memoization in dynamic programming?', options: ['Writing comments in code', 'Caching results of expensive function calls', 'Sorting data before processing', 'Allocating fixed memory blocks'], correctAnswer: 'Caching results of expensive function calls' },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'easy', question: 'What is a linked list?', options: ['An array with fixed size', 'A collection of nodes where each node points to the next', 'A type of binary tree', 'A hash map implementation'], correctAnswer: 'A collection of nodes where each node points to the next' },
  { category: 'DSA / Algorithms', type: 'boolean', difficulty: 'medium', question: 'Quick Sort is a stable sorting algorithm.', options: ['Yes', 'No'], correctAnswer: 'No' },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'hard', question: 'What does the "two-pointer" technique typically help optimize?', options: ['Graph traversals', 'String/array problems requiring O(n) instead of O(n²)', 'Tree balancing', 'Hash table resizing'], correctAnswer: 'String/array problems requiring O(n) instead of O(n²)' },
  { category: 'DSA / Algorithms', type: 'rating', difficulty: 'hard', question: 'Rate your experience with competitive programming platforms (LeetCode, Codeforces, etc.).', options: [] },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'medium', question: 'What is the worst-case time complexity of Quick Sort?', options: ['O(n log n)', 'O(n)', 'O(n²)', 'O(log n)'], correctAnswer: 'O(n²)' },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'easy', question: 'A queue follows which ordering principle?', options: ['LIFO', 'FIFO', 'FILO', 'Random'], correctAnswer: 'FIFO' },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'hard', question: 'Which algorithm is used to find strongly connected components in a directed graph?', options: ['Prim\'s Algorithm', 'Kruskal\'s Algorithm', 'Tarjan\'s Algorithm', 'Floyd-Warshall Algorithm'], correctAnswer: 'Tarjan\'s Algorithm' },
  { category: 'DSA / Algorithms', type: 'rating', difficulty: 'medium', question: 'How well can you analyze the time and space complexity of an algorithm?', options: [] },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'medium', question: 'What is a trie data structure used for?', options: ['Storing sorted integers', 'Efficient string prefix searches', 'Graph pathfinding', 'Priority queuing'], correctAnswer: 'Efficient string prefix searches' },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'hard', question: 'In the sliding window technique, what is being "slid"?', options: ['A sorted sub-array', 'A fixed or variable-size subarray/substring across the input', 'A pointer from right to left', 'A stack over a queue'], correctAnswer: 'A fixed or variable-size subarray/substring across the input' },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'medium', question: 'What is an AVL tree?', options: ['A tree where all nodes have exactly two children', 'A self-balancing BST maintaining height balance', 'A tree for trie-based search', 'A red-black tree variant'], correctAnswer: 'A self-balancing BST maintaining height balance' },
  { category: 'DSA / Algorithms', type: 'boolean', difficulty: 'easy', question: 'Insertion in a hash table with chaining has an average time complexity of O(1).', options: ['Yes', 'No'], correctAnswer: 'Yes' },
  { category: 'DSA / Algorithms', type: 'mcq', difficulty: 'hard', question: 'What does "NP-hard" mean?', options: ['The problem can be solved in polynomial time', 'The problem is at least as hard as any NP problem', 'The problem has no known solution', 'The problem runs in non-polynomial time always'], correctAnswer: 'The problem is at least as hard as any NP problem' },
  { category: 'DSA / Algorithms', type: 'rating', difficulty: 'medium', question: 'Rate your ability to implement graph algorithms (BFS, DFS, Dijkstra).', options: [] },

  // ── Data Science ──────────────────────────────────────────────────────────
  { category: 'Data Science', type: 'mcq', difficulty: 'medium', question: 'What does EDA stand for in data science?', options: ['Exploratory Data Analysis', 'External Data Application', 'Extended Data Aggregation', 'Empirical Data Alignment'], correctAnswer: 'Exploratory Data Analysis' },
  { category: 'Data Science', type: 'mcq', difficulty: 'hard', question: 'What is the difference between Type I and Type II errors?', options: ['Type I = false negative, Type II = false positive', 'Type I = false positive, Type II = false negative', 'Both are the same', 'Type I is a model error, Type II is a data error'], correctAnswer: 'Type I = false positive, Type II = false negative' },
  { category: 'Data Science', type: 'mcq', difficulty: 'medium', question: 'Which library is most commonly used for data manipulation in Python?', options: ['NumPy', 'Pandas', 'Matplotlib', 'Scikit-learn'], correctAnswer: 'Pandas' },
  { category: 'Data Science', type: 'boolean', difficulty: 'easy', question: 'A correlation of 0.95 between two variables implies one causes the other.', options: ['Yes', 'No'], correctAnswer: 'No' },
  { category: 'Data Science', type: 'mcq', difficulty: 'hard', question: 'What is regularization in machine learning?', options: ['Normalizing input features to 0-1', 'Adding a penalty term to reduce model complexity and prevent overfitting', 'Balancing class weights in a dataset', 'Splitting data into train/test sets'], correctAnswer: 'Adding a penalty term to reduce model complexity and prevent overfitting' },
  { category: 'Data Science', type: 'mcq', difficulty: 'medium', question: 'What does a confusion matrix help evaluate?', options: ['Model training speed', 'Classification model performance', 'Feature correlation', 'Data distribution'], correctAnswer: 'Classification model performance' },
  { category: 'Data Science', type: 'rating', difficulty: 'medium', question: 'Rate your proficiency with Python for data analysis (Pandas, NumPy).', options: [] },
  { category: 'Data Science', type: 'mcq', difficulty: 'hard', question: 'What is the bias-variance tradeoff?', options: ['Choosing between accuracy and speed', 'Balancing underfitting (high bias) and overfitting (high variance)', 'The tradeoff between training and test data size', 'Feature selection vs feature engineering'], correctAnswer: 'Balancing underfitting (high bias) and overfitting (high variance)' },
  { category: 'Data Science', type: 'mcq', difficulty: 'medium', question: 'Which technique is used to handle missing data?', options: ['One-hot encoding', 'Imputation', 'Feature scaling', 'PCA'], correctAnswer: 'Imputation' },
  { category: 'Data Science', type: 'rating', difficulty: 'hard', question: 'Rate your experience building end-to-end data science pipelines.', options: [] },
  { category: 'Data Science', type: 'mcq', difficulty: 'medium', question: 'What is the purpose of cross-validation?', options: ['Visualizing data distributions', 'Estimating model performance on unseen data', 'Encoding categorical features', 'Removing outliers'], correctAnswer: 'Estimating model performance on unseen data' },
  { category: 'Data Science', type: 'mcq', difficulty: 'easy', question: 'What does SQL stand for?', options: ['Structured Query Language', 'Simple Query Logic', 'Sequential Query Language', 'Standard Query List'], correctAnswer: 'Structured Query Language' },
  { category: 'Data Science', type: 'boolean', difficulty: 'medium', question: 'Gradient Boosting combines multiple weak learners to form a strong learner.', options: ['Yes', 'No'], correctAnswer: 'Yes' },
  { category: 'Data Science', type: 'mcq', difficulty: 'hard', question: 'What is Principal Component Analysis (PCA) used for?', options: ['Predicting continuous values', 'Dimensionality reduction while retaining variance', 'Clustering unlabeled data', 'Encoding categorical variables'], correctAnswer: 'Dimensionality reduction while retaining variance' },
  { category: 'Data Science', type: 'rating', difficulty: 'medium', question: 'Rate your ability to create data visualizations and present insights to non-technical stakeholders.', options: [] },
  { category: 'Data Science', type: 'mcq', difficulty: 'medium', question: 'Which metric is most appropriate for an imbalanced classification problem?', options: ['Accuracy', 'F1-Score', 'Mean Squared Error', 'R-squared'], correctAnswer: 'F1-Score' },
  { category: 'Data Science', type: 'mcq', difficulty: 'hard', question: 'What is A/B testing?', options: ['Comparing two versions of a model\'s algorithm', 'A statistical method for comparing two variants to determine which performs better', 'Testing on 50% of your dataset', 'Running code in two environments simultaneously'], correctAnswer: 'A statistical method for comparing two variants to determine which performs better' },
  { category: 'Data Science', type: 'mcq', difficulty: 'medium', question: 'What is the output layer activation function for binary classification?', options: ['ReLU', 'Sigmoid', 'Softmax', 'Tanh'], correctAnswer: 'Sigmoid' },
  { category: 'Data Science', type: 'boolean', difficulty: 'easy', question: 'Outliers should always be removed from a dataset before modeling.', options: ['Yes', 'No'], correctAnswer: 'No' },
  { category: 'Data Science', type: 'rating', difficulty: 'medium', question: 'Rate your experience with statistical hypothesis testing.', options: [] },
  { category: 'Data Science', type: 'mcq', difficulty: 'hard', question: 'What is the "curse of dimensionality"?', options: ['RAM running out during model training', 'Model performance degrading as feature count grows very large', 'Overly long training times', 'The issue of too many class labels'], correctAnswer: 'Model performance degrading as feature count grows very large' },
  { category: 'Data Science', type: 'mcq', difficulty: 'medium', question: 'What does RMSE measure?', options: ['Classification accuracy', 'Root mean squared error between predicted and actual values', 'The size of a dataset', 'Feature importance scores'], correctAnswer: 'Root mean squared error between predicted and actual values' },
  { category: 'Data Science', type: 'mcq', difficulty: 'medium', question: 'Which algorithm is an ensemble of decision trees?', options: ['K-Nearest Neighbors', 'Random Forest', 'Naive Bayes', 'Logistic Regression'], correctAnswer: 'Random Forest' },
  { category: 'Data Science', type: 'mcq', difficulty: 'hard', question: 'What is the purpose of the kernel trick in SVM?', options: ['To speed up training', 'To map data to a higher-dimensional space without explicit computation', 'To reduce overfitting', 'To scale features automatically'], correctAnswer: 'To map data to a higher-dimensional space without explicit computation' },
  { category: 'Data Science', type: 'rating', difficulty: 'hard', question: 'Rate your experience deploying machine learning models to production.', options: [] },

  // ── Machine Learning ──────────────────────────────────────────────────────
  { category: 'Machine Learning', type: 'mcq', difficulty: 'easy', question: 'What type of learning uses labeled training data?', options: ['Unsupervised Learning', 'Supervised Learning', 'Reinforcement Learning', 'Self-supervised Learning'], correctAnswer: 'Supervised Learning' },
  { category: 'Machine Learning', type: 'mcq', difficulty: 'hard', question: 'In a neural network, what does backpropagation compute?', options: ['The output layer predictions', 'Gradients of the loss with respect to weights', 'The activation of each layer', 'The optimal learning rate'], correctAnswer: 'Gradients of the loss with respect to weights' },
  { category: 'Machine Learning', type: 'mcq', difficulty: 'medium', question: 'What is dropout in deep learning used for?', options: ['Speeding up inference', 'Reducing overfitting by randomly deactivating neurons during training', 'Initializing weights to zero', 'Normalizing batch data'], correctAnswer: 'Reducing overfitting by randomly deactivating neurons during training' },
  { category: 'Machine Learning', type: 'boolean', difficulty: 'medium', question: 'Transfer learning allows a model trained on one task to be fine-tuned for another.', options: ['Yes', 'No'], correctAnswer: 'Yes' },
  { category: 'Machine Learning', type: 'mcq', difficulty: 'hard', question: 'What is the vanishing gradient problem?', options: ['Gradients becoming very large, causing instability', 'Gradients becoming too small to update earlier layers effectively', 'Loss function returning NaN values', 'The model memorizing training data'], correctAnswer: 'Gradients becoming too small to update earlier layers effectively' },
  { category: 'Machine Learning', type: 'mcq', difficulty: 'medium', question: 'Which optimizer adapts the learning rate for each parameter individually?', options: ['SGD', 'Momentum', 'Adam', 'RMSProp'], correctAnswer: 'Adam' },
  { category: 'Machine Learning', type: 'rating', difficulty: 'medium', question: 'Rate your experience training neural networks with PyTorch or TensorFlow.', options: [] },
  { category: 'Machine Learning', type: 'mcq', difficulty: 'medium', question: 'What does CNN stand for in deep learning?', options: ['Compressed Neural Network', 'Convolutional Neural Network', 'Cyclic Node Network', 'Connected Node Network'], correctAnswer: 'Convolutional Neural Network' },
  { category: 'Machine Learning', type: 'mcq', difficulty: 'hard', question: 'What is attention mechanism in transformers?', options: ['Focusing training on hard samples', 'Computing weighted importance of different input positions', 'A method to reduce model size', 'Early stopping criterion'], correctAnswer: 'Computing weighted importance of different input positions' },
  { category: 'Machine Learning', type: 'rating', difficulty: 'hard', question: 'Rate your ability to select appropriate ML algorithms for different problem types.', options: [] },
  { category: 'Machine Learning', type: 'mcq', difficulty: 'medium', question: 'What is batch normalization?', options: ['Splitting data into batches', 'Normalizing activations within a mini-batch to stabilize training', 'Normalizing input features once before training', 'Reducing batch size dynamically'], correctAnswer: 'Normalizing activations within a mini-batch to stabilize training' },
  { category: 'Machine Learning', type: 'boolean', difficulty: 'easy', question: 'K-Means clustering requires specifying the number of clusters (k) beforehand.', options: ['Yes', 'No'], correctAnswer: 'Yes' },
  { category: 'Machine Learning', type: 'mcq', difficulty: 'hard', question: 'What is the main advantage of XGBoost over standard gradient boosting?', options: ['It uses neural networks internally', 'It includes regularization and parallel processing for better performance', 'It is unsupervised', 'It requires no hyperparameter tuning'], correctAnswer: 'It includes regularization and parallel processing for better performance' },
  { category: 'Machine Learning', type: 'mcq', difficulty: 'medium', question: 'What is an ROC curve used for?', options: ['Visualizing training loss', 'Evaluating binary classifier performance across all thresholds', 'Showing feature importance', 'Comparing multiple regression models'], correctAnswer: 'Evaluating binary classifier performance across all thresholds' },
  { category: 'Machine Learning', type: 'rating', difficulty: 'medium', question: 'How comfortable are you with hyperparameter tuning techniques (Grid Search, Random Search, Bayesian Optimization)?', options: [] },
  { category: 'Machine Learning', type: 'mcq', difficulty: 'hard', question: 'What is the difference between a generative and discriminative model?', options: ['Generative models are faster; discriminative are more accurate', 'Generative models learn joint probability P(X,Y); discriminative learn P(Y|X)', 'They are the same thing', 'Discriminative models can generate new data samples'], correctAnswer: 'Generative models learn joint probability P(X,Y); discriminative learn P(Y|X)' },
  { category: 'Machine Learning', type: 'mcq', difficulty: 'easy', question: 'What is feature engineering?', options: ['Building new features from raw data to improve model performance', 'Training a model on engineered datasets', 'Removing features from a model', 'Selecting the best model architecture'], correctAnswer: 'Building new features from raw data to improve model performance' },
  { category: 'Machine Learning', type: 'mcq', difficulty: 'medium', question: 'Reinforcement learning trains an agent to maximize which signal?', options: ['A predefined loss function', 'Cumulative reward from the environment', 'Labeled ground truth data', 'Reconstruction error'], correctAnswer: 'Cumulative reward from the environment' },
  { category: 'Machine Learning', type: 'boolean', difficulty: 'medium', question: 'BERT is a transformer-based model pre-trained on a masked language modeling objective.', options: ['Yes', 'No'], correctAnswer: 'Yes' },
  { category: 'Machine Learning', type: 'rating', difficulty: 'hard', question: 'Rate your understanding of NLP tasks (text classification, NER, question answering).', options: [] },
  { category: 'Machine Learning', type: 'mcq', difficulty: 'hard', question: 'What does RLHF stand for in the context of large language models?', options: ['Reinforcement Learning from Human Feedback', 'Recursive Large History Finetuning', 'Regularized Language Hierarchical Framework', 'Recurrent Learning Hybrid Framework'], correctAnswer: 'Reinforcement Learning from Human Feedback' },
  { category: 'Machine Learning', type: 'mcq', difficulty: 'medium', question: 'What is the purpose of a validation set during model training?', options: ['To compute the final test accuracy', 'To tune hyperparameters and monitor for overfitting', 'To augment training data', 'To normalize input features'], correctAnswer: 'To tune hyperparameters and monitor for overfitting' },
  { category: 'Machine Learning', type: 'mcq', difficulty: 'medium', question: 'Which activation function is commonly used in the output layer of multi-class classification?', options: ['ReLU', 'Sigmoid', 'Softmax', 'Tanh'], correctAnswer: 'Softmax' },

  // ── Backend / Node.js ─────────────────────────────────────────────────────
  { category: 'Backend / Node.js', type: 'mcq', difficulty: 'medium', question: 'What is middleware in Express.js?', options: ['A database ORM', 'A function with access to request, response, and next()', 'An HTTP client for making API calls', 'A module bundler'], correctAnswer: 'A function with access to request, response, and next()' },
  { category: 'Backend / Node.js', type: 'mcq', difficulty: 'hard', question: 'What is the event loop in Node.js responsible for?', options: ['Compiling JavaScript to bytecode', 'Handling asynchronous I/O operations without blocking', 'Managing memory allocation', 'Running worker threads in parallel'], correctAnswer: 'Handling asynchronous I/O operations without blocking' },
  { category: 'Backend / Node.js', type: 'mcq', difficulty: 'medium', question: 'What HTTP method is typically used for updating a resource partially?', options: ['PUT', 'POST', 'PATCH', 'DELETE'], correctAnswer: 'PATCH' },
  { category: 'Backend / Node.js', type: 'boolean', difficulty: 'easy', question: 'MongoDB is a relational database.', options: ['Yes', 'No'], correctAnswer: 'No' },
  { category: 'Backend / Node.js', type: 'mcq', difficulty: 'hard', question: 'What is the purpose of database indexing?', options: ['Encrypting stored data', 'Speeding up query operations on large collections', 'Backing up the database', 'Normalizing data relationships'], correctAnswer: 'Speeding up query operations on large collections' },
  { category: 'Backend / Node.js', type: 'rating', difficulty: 'medium', question: 'Rate your ability to design scalable REST APIs.', options: [] },
  { category: 'Backend / Node.js', type: 'mcq', difficulty: 'medium', question: 'What does ORM stand for?', options: ['Object Response Model', 'Object Relational Mapping', 'Optimized Resource Manager', 'Output Rendering Module'], correctAnswer: 'Object Relational Mapping' },
  { category: 'Backend / Node.js', type: 'mcq', difficulty: 'hard', question: 'What is the N+1 query problem?', options: ['Running N queries in parallel', 'Executing one query to get N records, then N additional queries for related data', 'Adding 1 to every SQL result', 'Pagination issue in REST APIs'], correctAnswer: 'Executing one query to get N records, then N additional queries for related data' },
  { category: 'Backend / Node.js', type: 'mcq', difficulty: 'medium', question: 'What is JWT used for in REST APIs?', options: ['Rate limiting', 'Stateless authentication and authorization', 'Data encryption at rest', 'Database migrations'], correctAnswer: 'Stateless authentication and authorization' },
  { category: 'Backend / Node.js', type: 'rating', difficulty: 'hard', question: 'Rate your experience with microservices architecture.', options: [] },
  { category: 'Backend / Node.js', type: 'mcq', difficulty: 'medium', question: 'What is Redis commonly used for?', options: ['Serving static files', 'In-memory caching and session storage', 'Object storage for large files', 'Message queue serialization only'], correctAnswer: 'In-memory caching and session storage' },
  { category: 'Backend / Node.js', type: 'boolean', difficulty: 'medium', question: 'WebSockets provide full-duplex communication between client and server.', options: ['Yes', 'No'], correctAnswer: 'Yes' },
  { category: 'Backend / Node.js', type: 'mcq', difficulty: 'hard', question: 'What is the CAP theorem?', options: ['A theorem about CPU performance', 'Distributed systems can guarantee only 2 of: Consistency, Availability, Partition tolerance', 'A caching policy for REST APIs', 'A database normalization rule'], correctAnswer: 'Distributed systems can guarantee only 2 of: Consistency, Availability, Partition tolerance' },
  { category: 'Backend / Node.js', type: 'mcq', difficulty: 'medium', question: 'What does ACID stand for in database transactions?', options: ['Atomicity, Consistency, Isolation, Durability', 'Availability, Concurrency, Integrity, Distribution', 'Atomicity, Concurrency, Indexing, Duplication', 'Asynchronous, Consistent, Independent, Durable'], correctAnswer: 'Atomicity, Consistency, Isolation, Durability' },
  { category: 'Backend / Node.js', type: 'rating', difficulty: 'medium', question: 'Rate your proficiency with Docker and containerization.', options: [] },
  { category: 'Backend / Node.js', type: 'mcq', difficulty: 'hard', question: 'What is the purpose of a message queue (e.g., RabbitMQ, Kafka)?', options: ['To store database records', 'To decouple services and enable async communication', 'To cache API responses', 'To manage user sessions'], correctAnswer: 'To decouple services and enable async communication' },

  // ── UI/UX Design ──────────────────────────────────────────────────────────
  { category: 'UI/UX Design', type: 'mcq', difficulty: 'easy', question: 'What does UX stand for?', options: ['User Excitement', 'User Experience', 'Unified Exchange', 'User Execution'], correctAnswer: 'User Experience' },
  { category: 'UI/UX Design', type: 'mcq', difficulty: 'medium', question: 'What is a wireframe?', options: ['A high-fidelity prototype with colors and assets', 'A low-fidelity skeletal layout showing structure and flow', 'A CSS framework for layout', 'A user research document'], correctAnswer: 'A low-fidelity skeletal layout showing structure and flow' },
  { category: 'UI/UX Design', type: 'rating', difficulty: 'medium', question: 'Rate your proficiency with Figma or Adobe XD for UI design.', options: [] },
  { category: 'UI/UX Design', type: 'mcq', difficulty: 'hard', question: 'What is the primary goal of usability testing?', options: ['To identify design trends', 'To observe real users interacting with a product and find pain points', 'To compare competitors\' products', 'To gather stakeholder feedback on aesthetics'], correctAnswer: 'To observe real users interacting with a product and find pain points' },
  { category: 'UI/UX Design', type: 'boolean', difficulty: 'easy', question: 'The "8px grid system" helps maintain consistent spacing in UI design.', options: ['Yes', 'No'], correctAnswer: 'Yes' },
  { category: 'UI/UX Design', type: 'mcq', difficulty: 'medium', question: 'What is the purpose of a design system?', options: ['To speed up developer builds', 'To maintain consistent UI components, styles, and patterns across a product', 'To define database schemas', 'To automate user testing'], correctAnswer: 'To maintain consistent UI components, styles, and patterns across a product' },
  { category: 'UI/UX Design', type: 'mcq', difficulty: 'hard', question: 'What is "cognitive load" in UX?', options: ['The time to load a web page', 'The mental effort required for a user to understand and interact with an interface', 'Memory used by the browser', 'The number of design decisions made'], correctAnswer: 'The mental effort required for a user to understand and interact with an interface' },
  { category: 'UI/UX Design', type: 'rating', difficulty: 'hard', question: 'Rate your ability to conduct and analyze user research (interviews, surveys, A/B tests).', options: [] },
  { category: 'UI/UX Design', type: 'mcq', difficulty: 'medium', question: 'What is the contrast ratio requirement for normal text per WCAG AA accessibility standards?', options: ['2:1', '3:1', '4.5:1', '7:1'], correctAnswer: '4.5:1' },
  { category: 'UI/UX Design', type: 'mcq', difficulty: 'medium', question: 'What does "affordance" mean in UX design?', options: ['How fast a page loads', 'A design element that suggests how it should be used', 'Color contrast ratio', 'The number of user touch points'], correctAnswer: 'A design element that suggests how it should be used' },
  { category: 'UI/UX Design', type: 'boolean', difficulty: 'medium', question: 'Hick\'s Law states that more choices increase decision-making time.', options: ['Yes', 'No'], correctAnswer: 'Yes' },
  { category: 'UI/UX Design', type: 'mcq', difficulty: 'hard', question: 'What is the difference between UX and UI?', options: ['They are the same thing', 'UX focuses on user journey and feel; UI focuses on visual elements and interaction', 'UX is for mobile; UI is for web', 'UI involves user research; UX is only visual'], correctAnswer: 'UX focuses on user journey and feel; UI focuses on visual elements and interaction' },
  { category: 'UI/UX Design', type: 'rating', difficulty: 'medium', question: 'Rate your experience creating responsive designs for multiple screen sizes.', options: [] },
  { category: 'UI/UX Design', type: 'mcq', difficulty: 'medium', question: 'What is a user persona?', options: ['A fake social media account', 'A semi-fictional representation of your ideal user based on research', 'A list of user requirements', 'An accessibility profile'], correctAnswer: 'A semi-fictional representation of your ideal user based on research' },
];

async function seed() {
  try {
    await connectDB();

    const existing = await QuestionBank.countDocuments();
    if (existing > 0) {
      console.log(`⚠️  Question bank already has ${existing} questions. Skipping seed.`);
      console.log('   To re-seed, first clear the collection manually.');
      process.exit(0);
    }

    const inserted = await QuestionBank.insertMany(questions);
    console.log(`✅ Seeded ${inserted.length} questions across domains:`);

    const categories = [...new Set(questions.map(q => q.category))];
    for (const cat of categories) {
      const count = questions.filter(q => q.category === cat).length;
      console.log(`   • ${cat}: ${count} questions`);
    }

    process.exit(0);
  } catch (err) {
    console.error('❌ Seeding failed:', err.message);
    process.exit(1);
  }
}

seed();
